version: '3.9'
services:
  accounts:
    build: ./Dockerfile
    container_name: accounts
    command: go run ./...
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
    restart: always
